# Core Colors
background            #121318
foreground            #ffffff
selection_foreground  #ecefff
selection_background  #000000
cursor                #ecefff
cursor_text_color     #121318

# Regular Colors
color0  #121318
color1  #ffece9
color2  #ecefff
color3  #ffeafb
color4  #000000
color5  #000000
color6  #ecefff
color7  #ffffff

# Bright Colors
color8  #4f5056
color9  #ffece9
color10 #ecefff
color11 #ffeafb
color12 #000000
color13 #000000 
color14 #ecefff
color15 #ffffff
